server {
    listen 80;
    server_name surokw.myddns.me;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name surokw.myddns.me;
    client_max_body_size 20M;

    resolver 127.0.0.11 valid=10s;
    set $backend_upstream backend:8000;

    ssl_certificate /etc/letsencrypt/live/surokw.myddns.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/surokw.myddns.me/privkey.pem;

    location /api/docs/ {
        root /usr/share/nginx/html/build;
        try_files $uri $uri/redoc.html;
    }
    location /api/ {
        proxy_set_header Host $host;
        proxy_pass http://$backend_upstream;
    }
    location /admin/ {
        proxy_set_header Host $host;
        proxy_pass http://$backend_upstream;
    }
    location /s/ {
        proxy_set_header Host $host;
        proxy_pass http://$backend_upstream;
    }
    location /static/ {
        root /usr/share/nginx/html/build;
    }
    location /media/ {
        alias /var/html/media/;
    }
    location / {
        root /usr/share/nginx/html/build;
        index index.html index.htm;
        try_files $uri /index.html;
    }
}
